// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nSEMY4QToSkIAvAJbKu4FrCkyqaE80c',
    appId: '1:870186875900:web:0b84f6c5845d75506e5079',
    messagingSenderId: '870186875900',
    projectId: 'smart-campus-navigation-3cd05',
    authDomain: 'smart-campus-navigation-3cd05.firebaseapp.com',
    storageBucket: 'smart-campus-navigation-3cd05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUOVxdKNXkJxQHKYflObnLKBqIoQOmkX4',
    appId: '1:870186875900:android:2e593a8a675d1a276e5079',
    messagingSenderId: '870186875900',
    projectId: 'smart-campus-navigation-3cd05',
    storageBucket: 'smart-campus-navigation-3cd05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxgRxaIle5t4vzAe79OeP8l-WGdtlQIxM',
    appId: '1:870186875900:ios:5e48c8a4fd0a368b6e5079',
    messagingSenderId: '870186875900',
    projectId: 'smart-campus-navigation-3cd05',
    storageBucket: 'smart-campus-navigation-3cd05.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusNavigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxgRxaIle5t4vzAe79OeP8l-WGdtlQIxM',
    appId: '1:870186875900:ios:5e48c8a4fd0a368b6e5079',
    messagingSenderId: '870186875900',
    projectId: 'smart-campus-navigation-3cd05',
    storageBucket: 'smart-campus-navigation-3cd05.firebasestorage.app',
    iosBundleId: 'com.example.smartCampusNavigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7nSEMY4QToSkIAvAJbKu4FrCkyqaE80c',
    appId: '1:870186875900:web:2e1605607860edbf6e5079',
    messagingSenderId: '870186875900',
    projectId: 'smart-campus-navigation-3cd05',
    authDomain: 'smart-campus-navigation-3cd05.firebaseapp.com',
    storageBucket: 'smart-campus-navigation-3cd05.firebasestorage.app',
  );
}
